config/routes.rb
Rails.application.routes.draw do
  root :to => 'homes#top'
  get '/top' => 'homes#top'
  get 'books' => 'books#index'
  post 'books' => 'books#create'
  get 'books/:id' => 'books#show', as: 'book'
  get 'books/:id/edit' => 'books#edit', as: 'edit_book'
  patch 'books/:id' => 'books#update',as: 'update_book'
  delete 'books/:id' => 'books#destroy', as: 'destroy_book'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord

  validates :title, presence: true
  validates :body, presence: true
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def index
    @books = Book.all
    @book = Book.new
    
  end
  
  def create
    @book = Book.new(book_params)
    if @book.save
       flash[:notice] = "Book was successfully created."
       redirect_to book_path(@book.id)
    else
       @books = Book.all
       render :index
    end
  end

  def show
    @book = Book.find(params[:id])
  end

  def edit
    @book = Book.find(params[:id])
  end
  
  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
       flash[:notice] = "Book was successfully updated."
       redirect_to book_path(@book.id)
    else
       @books = Book.all
       render :edit
    end
  end
  
  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to '/books'
  end

  private
  
  def book_params
    params.require(:book).permit(:title, :body)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/books/edit.html.erb
<h1>Editing Book</h1>

<% if @book.errors.any? %>
  <%= @book.errors.count %>errors prohibited this book from being saved:
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<%= form_with model: @book, url: update_book_path(@book.id), method: :patch do |f| %>

 <h4>Title</h4>
 <%= f.text_field :title %>
 
 <h4>Body</h4>
 <%= f.text_area :body %>
 
 <br>
 <%= f.submit 'Update Book' %>
 
<% end %>

<%= link_to "Show", book_path(@book.id) %>
<%= "|" %>
<%= link_to "Back", "/books" %>

app/views/books/index.html.erb
<h1>Books</h1>

<table>
<thead>
  <tr>
   <th>Title</th>
   <th>Body</th>
   <th colspan='3'></th>
  </tr>
 </thead>
 <tbody>
 <% @books.each do |book| %>
  <tr>
   <td>
    <%= book.title %>
   </td>
   <td>
    <%= book.body %>
   </td>
   <td>
    <%= link_to "Show", book_path(book.id) %>
   </td>
   <td>
    <%= link_to "Edit", edit_book_path(book.id) %>
   </td>
   <td>
    <%= link_to "Destroy", destroy_book_path(book.id), method: :delete, "data-confirm" => "Are you sure?" %>
   </td>
  </tr>
 <% end %>
 </tbody>
</table>


<h2>New Book</h2>
<% if @book.errors.any? %>
  <%= @book.errors.count %>errors prohibited this book from being saved:
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<%= form_with model: @book do |f| %>
 <h4>Title</h4>
 <%= f.text_field :title %>
 <h4>Body</h4>
 <%= f.text_area :body %>
 <br>
 <%= f.submit 'Create Book' %>
<% end %>

app/views/books/new.html.erb
<h1>Books</h1>
<table>
 <thead>
  <tr>
   <th>Title</th>
   <th>Body</th>
   <th colspan="3"></th>
  </tr>
 </thead>
 <tbody>
  <tr>
   <td>リーダブルコード</td>
   <td>より良いコードを書くためのシンプルで実践的なテクニック</td>
   <td>
    <a class="show_80837" href="/books/80837">Show</a>
   </td>
   <td>
    <a class="edit_80837" href="/books/80837/edit">Edit</a>
   </td>
   <td>
    <a data-confirm="Are you sure?" class="destroy_80837" rel="nofollow" data-method="delete" href="/books/80837">Destroy</a>
   </td>
  </tr>
  <tr>
   <td>トラブル知らずのシステム設計</td>
   <td>システム設計の要点を図解で説明してくれます</td>
   <td>
    <a class="show_80838" href="/books/80838">Show</a>
   </td>
   <td>
    <a class="edit_80838" href="/books/80838/edit">Edit</a>
   </td>
   <td>
    <a data-confirm="Are you sure?" class="destroy_80838" rel="nofollow" data-method="delete" href="/books/80838">Destroy</a>
   </td>
  </tr>
  <tr>
   <td>たのしいRuby</td>
   <td>Rubyの入門におすすめです</td>
   <td>
    <a class="show_80839" href="/books/80839">Show</a>
   </td>
   <td>
    <a class="edit_80839" href="/books/80839/edit">Edit</a>
   </td>
   <td>
    <a data-confirm="Are you sure?" class="destroy_80839" rel="nofollow" data-method="delete" href="/books/80839">Destroy</a>
   </td>
  </tr>
  <tr>
   <td>入門Git</td>
   <td>gitについての基本操作から内部構造まで解説してくれます</td>
   <td>
    <a class="show_80840" href="/books/80840">Show</a>
   </td>
   <td>
    <a class="edit_80840" href="/books/80840/edit">Edit</a>
   </td>
   <td>
    <a data-confirm="Are you sure?" class="destroy_80840" rel="nofollow" data-method="delete" href="/books/80840">Destroy</a>
   </td>
  </tr>
  <tr>
   <td>アルゴリズム図鑑</td>
   <td>アルゴリズムについてカラーイラストでしっかり解説してくれます</td>
   <td>
    <a class="show_80841" href="/book/80841">Show</a>
   </td>
   <td>
    <a class="edit_80841" href="/books/80841/edit">Edit</a>
   </td>
   <td>
    <a data-confirm="Are you sure?" class="destroy_80841" rel="nofollow" data-method="delete" href="/books/80841">Destroy</a>
   </td>
  </tr>
  <tr>
   <td>達人プログラマー</td>
   <td>プログラマ入門者は必読！</td>
   <td>
    <a class="show_80842" href="/books/80842">Show</a>
   </td>
   <td>
    <a class="edit_80842" href="/books/80842/edit">Edit</a>
   </td>
   <td>
    <a data-confirm="Are you sure?" class="destroy_80842" rel="nofollow" data-method="delete" href="/books/80842">Destroy</a>
   </td>
  </tr>
  <tr>
   <td>データベース実践入門</td>
   <td>効率的なSQL文を教えてくれます</td>
   <td>
    <a class="show_80843" href="/books/80843">Show</a>
   </td>
   <td>
    <a class="edit_80843" href="/books/80843/edit">Edit</a>
   </td>
   <td>
    <a data-confirm="Are you sure?" class="destroy_80843" rel="nofollow" data-method="delete" href="/books/80843">Destroy</a>
   </td>
  </tr>
 </tbody>
</table>

<h2>New Book</h2>
<%= form_with model: Book.new do |f| %>
 <h4>Title</h4>
 <%= f.text_field :title %>
 <h4>Body</h4>
 <%= f.text_area :body %>
 <%= f.submit 'Create Book' %>
<% end %>

app/views/books/show.html.erb
<% if flash[:notice] %>
<p><%= flash[:notice] %></p>
<% end %>

<p>
    <strong>Title:</strong>
    <%= @book.title %>
</p>

<p>
    <strong>Body:</strong>
    <%= @book.body %>
</p>

<%= link_to "Edit", edit_book_path %>
<%= "|" %>
<%= link_to "Back", "/books" %>

app/views/homes/top.html.erb
<h1>
    ようこそ
    <strong>Bookers</strong>
    へ！
</h1>
<p>
    <strong>Bookers</strong>
    では、さまざまな書籍に関するあなたの意見や
</p>
<p>印象を共有し交換することができます</p>
<p>
    <a href="/books">start</a>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>